repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 . --count --select=E9,F63,F7,F82 --ignore=E203,E501,F401,F403 --show-source --statistics
        language: system
        always_run: true
        pass_filenames: false

      - id: create requirements
        name: create requirements
        entry: sh write_requirements.sh
        language: system
        always_run: true
        pass_filenames: false
